# Generated by Django 4.2.25 on 2026-01-31 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('industry', models.CharField(blank=True, max_length=120)),
                ('company_type', models.CharField(blank=True, choices=[('public', 'Public company'), ('private', 'Private company'), ('nonprofit', 'Nonprofit'), ('government', 'Government'), ('self_employed', 'Self-employed'), ('other', 'Other')], max_length=20)),
                ('company_size', models.CharField(blank=True, choices=[('1-10', '1-10 employees'), ('11-50', '11-50 employees'), ('51-200', '51-200 employees'), ('201-500', '201-500 employees'), ('501-1000', '501-1,000 employees'), ('1001-5000', '1,001-5,000 employees'), ('5001-10000', '5,001-10,000 employees'), ('10000+', '10,000+ employees')], max_length=20)),
                ('headquarters', models.CharField(blank=True, max_length=200)),
                ('founded_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('specialties', models.TextField(blank=True)),
                ('logo_url', models.URLField(blank=True)),
                ('cover_url', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
